services:
  login-service:
    build: 
      context: ./microservicio-login
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=tu_clave_secreta_aqui
      - PRODUCT_SERVICE_URL=http://product-service:5000
      - DATABASE_URL=sqlite:////app/data/users.db
    volumes:
      - login-db:/app/data
    networks:
      - microservices-network
    restart: unless-stopped

  product-service:
    build:
      context: ./microservicio-productos
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_URI=postgresql+psycopg2://neondb_owner:npg_1inZKDP4xHah@ep-winter-credit-a5ve8b3o-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
      - LOGIN_SERVICE_URL=http://login-service:5000
    volumes:
      - ./microservicio-productos:/app
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  login-db:

networks:
  microservices-network:
    driver: bridge